<template>
  <div class="recommendations-footer">
    <!-- Recommendations -->
    <h2>Recommendations</h2>
    <div class="info-box">
      <div
        v-for="(rec, index) in recommendations"
        :key="`rec-${index}`"
        class="info-item page-break-avoid"
      >
        <div class="info-label">{{ rec.category }}</div>
        <div class="info-value">{{ rec.title }}</div>
        <p>{{ rec.description }}</p>
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <p>
        © 2025 {{ systemName }} | Generated by UniFi Network Controller v{{
          controllerVersion
        }}
      </p>
      <p>Report period: {{ reportPeriod }}</p>
    </div>
  </div>
</template>

<script>
export default {
  name: "RecommendationsFooter",

  props: {
    recommendations: {
      type: Array,
      required: true,
    },
    systemName: {
      type: String,
      required: true,
    },
    controllerVersion: {
      type: String,
      required: true,
    },
    reportPeriod: {
      type: String,
      required: true,
    },
  },
};
</script>
